server:
  port: 9112
spring:
  application:
    name: spring-cloud-consumer
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false