server:
  port: 9010
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password: