server:
  port: 9011
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lijiakui/spring-cloud-examples/
          search-paths: spring-cloud-base/config-repo
          username: jackcoder@126.com
          password: lijiakui861224
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
management:
  security:
    enabled: false